name: Upload Artifacts (Windows)

on:
  workflow_dispatch:

jobs:
  upload-artifacts:
    uses: ./.github/workflows/nexus-upload-reusable.yml
    with:
      url: ${{ secrets.UPLOAD_URL }}
      remotePath: 'upload/${{ github.run_id }}/'
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      sourcePath: './.github/upload Artifacts/'
      files: '*.zip'
      retry: 3
