name: Upload Artifacts (Windows)

on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs:
  upload-artifacts:
    uses: ./.github/workflows/nexus-upload-reusable.yml
    secrets: 
      url: ${{ secrets.UPLOAD_URL }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
    with:
      remotePath: 'upload/${{ github.run_id }}/'
      sourcePath: './.github/uploadArtifacts/'
      files: '*.zip'
      retry: 3
      
