name: Upload Artifacts (Windows)

on:  
  push:  
    branches:  
      - main
  #workflow_dispatch:  

jobs:
  upload-artifacts:
    uses: ./.github/workflows/nexus-upload-reusable.yml
    with:
      runsOn: windows-latest
      remotePath: 'repository/hextesting'  # Input for remote path
      sourcePath: './.github/uploadArtifacts/'  # Input for source path
      files: '*.zip'  # Input for files to upload
      retry: 3  # Input for retry count
      username: ${{ secrets.USERNAME }}  # Pass the secret username
      password: ${{ secrets.PASSWORD }}  # Pass the secret password
      url: ${{ secrets.UPLOAD_URL }}  # Pass the secret URL
