name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  npm-workflow:
    uses: ./.github/workflows/reusable-npm.yml
    with:
      command: install
      verbose: true
      customCommand: build
      customRegistry: https://custom.registry.url
      customFeed: feed-name
      customEndpoint: https://custom.endpoint.url
      publishRegistry: https://publish.registry.url
      publishFeed: publish-feed-name
      publishEndpoint: https://publish.endpoint.url
