name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: kirandevops1993/VS-TEST-REUSABLE-/.github/workflows/VStest-reusable.yml@main
    with:
      vsTestVersion: "16.0"
      testAssembly: "*Tests.dll"
      testFilterCriteria: "TestCategory=Unit"
      runSettingsFile: "test.runsettings"
      codeCoverageEnabled: true
      pathToCustomTestAdapters: ""
      overrideTestRunParameters: ""
      publishRunAttachments: true
      runInParallel: true
      testRunTitle: "Unit Tests"
      platform: "x64"
      configuration: "Release"
      otherConsoleOptions: "/logger:trx"
