name: node install
 
on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

  
jobs:
  call-reusable:
    #uses: ./.github/workflows/reusable-node-windows.yml
    uses: ./.github/workflows/node-choco.yml
    with:
      version: '16.13.0'
