name: Main Publish Workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs: 
  call-reusable: 
    uses: ./.github/workflows/npmtask-reusable.yml
    
    with: 
      command: "npm install" 
      working_dir: "./src" 
      verbose: true 
      custom_command: "npm run build" 
      custom_registry: "https://registry.npmjs.org/" 
     
