name: Main Publish Workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs: 
  call-reusable: 
    uses: kirandevops1993/NPM-REUSABLE-/.github/workflows/npmtask-reusable.yml@main 
    with: 
      command: "npm install" 
      working_dir: "./src" 
      verbose: true 
      custom_command: "npm cache clean --force" 
      custom_registry: "https://custom.registry.url" 
     
