
name: Main MSBuild Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: kirandevops1993/MS-BUILD-TASKS-REUSABLE-/.github/workflows/msbuildtasks-reusable.yml@main
    with:
      platform: 'x64'
      configuration: 'Release'
      clean: true
      maxCpu: 4
      msBuildArgs: '/p:DeployOnBuild=true /p:PublishProfile=Release'
