name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: kirandevops1993/VS-TEST-REUSABLE/.github/workflows/VStest-reusable.yml@main
    with:
      dotnet-version: "6.0.x"  # Ensure this matches the .NET version used in your project
      test-assembly: "**/*Tests.dll"  # Ensures all test assemblies are discovered
      test-filter-criteria: "TestCategory=Unit"
      run-settings-file: "test.runsettings"
      code-coverage-enabled: true
      path-to-custom-test-adapters: ""
      override-test-run-parameters: ""
      publish-run-attachments: true
      run-in-parallel: true
      test-run-title: "Unit Tests"
      platform: "x64"
      configuration: "Release"
      other-console-options: "/logger:trx"
