name: NVM Main Workflow
 
on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 
 
jobs:
  call-reusable:
    uses: ./.github/workflows/nvm-reusable.yml
    with:
      version: '20.11.1'
      checkLatest: false
