name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-build:
    uses: kirandevops1993/REUSABLE-.NET-REPO-/.github/workflows/msbuild-reusable.yml@main
    with:
      solution_path: 'AspnetCoreMvcFull.sln'
      project_path: 'AspnetCoreMvcFull.csproj'
      build_configuration: 'Release'

