name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  npm-workflow:
    uses: kirandevops1993/NPM-REUSABLE-/.github/workflows/npmtask-reusable.yml@main
    with:
      command: install
      workingDir: ./my-app
      verbose: true
      customCommand: build
      customRegistry: https://custom.registry.url
      customFeed: feed-name
      customEndpoint: https://custom.endpoint.url
      publishRegistry: https://publish.registry.url
      publishFeed: publish-feed-name
      publishEndpoint: https://publish.endpoint.url
      sensitiveInfo: ${{ secrets.SENSITIVE_ALPHANUMERIC_INFO_1 }}
