name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test-job:
    uses: ./.github/workflows/vstest-reusable.yml
    with:
      dotnet-version: "6.0"
      test-assembly: "**/*Tests.dll"
      test-filter-criteria: "TestCategory=SmokeTests"
      configuration: "Release"
      platform: "x64"
      run-settings-file: "test.runsettings"
      code-coverage-enabled: true
      test-run-title: "MyTestRun"
      custom-test-adapters: "test-adapters/NUnit"  
