name: MSBuild Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: kirandevops1993/MS-BUILD-TASKS-REUSABLE/.github/workflows/msbuildtasks-reusable.yml@main
    with:
      platform: "x64"
      configuration: "Release"
      maxCpu: 8
      clean: true
      msbuildArguments: ""
      createLogFile: true
      logFileVerbosity: "detailed"
