name: node install
 
on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

  
jobs:
  call-reusable:
    #uses: ./.github/workflows/reusable-node-windows.yml
    uses: ./.github/workflows/node-choco.yml
    with:
      version: | 
        18.20.4
        18.19.1
        18.20.1
        15.0.0
        15.2.0
        15.4.0
