name: Main Publish Workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs: 
  call-reusable: 
    uses: ./.github/workflows/npmtask-reusable.yml
    
    with: 
      command: "install" 
      workingDir: "./.github/workflows/" 
      verbose: true 
      customCommand: "run build" 
      customRegistry: "https://registry.npmjs.org/" 
     
