
name: Main MSBuild Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/msbuild-reusable.yml  
    with:
      platform: 'x64'
      configuration: 'Release'
      clean: true
      maxCpu: 4
      msBuildArgs: '/p:DeployOnBuild=true /p:PublishProfile=Release'
