name: Setup Node with choco on Windows with NVM
 
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
 
jobs:
  setup-node:
    runs-on: windows-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: node version
        run: node -v
         
         
      - name: Install NVM via Chocolatey
        
        run: |
         choco install nvm -y
         choco list --localonly
         choco info nvm
         Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
         refreshenv
         Get-ChildItem -Path "C:\ProgramData\chocolatey\lib\nvm.install\tools" -Recurse
         Get-ChildItem -Path "C:\ProgramData\chocolatey\lib\nvm\tools" -Recurse
         Get-ChildItem -Path "C:\ProgramData\chocolatey\lib\nvm" -Recurse
         
 
      - name: Install and Use Node.js via NVM
        run: |
          nvm install ${{ inputs.version }}
          nvm use ${{ inputs.version }}
          node -v
          npm -v
