name: Setup Node on Windows with NVM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Step 1: Check if the requested Node.js version exists in versions.txt
      - name: Check if version exists in list
        id: check_version
        run: |
          $versionInput = "${{ inputs.version }}"
          $versionList = Get-Content "versions.txt"
          $match = $versionList | Where-Object { $_ -eq $versionInput }
         
          if (-not $match) {
            Write-Error " Version $versionInput is not allowed. Exiting."
            exit 1
          } else {
            Write-Host " Version $versionInput is valid."
          }
 
          
