name: Setup Node on Windows with NVM

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string

jobs:
  setup-node:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install NVM via Chocolatey
      - name: Install NVM via Chocolatey
        run: choco install nvm -y

      # Step 3: Add NVM and Node.js to PATH
      - name: Add NVM and Node.js to PATH
        shell: powershell
        run: |
          echo "C:\ProgramData\nvm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\nodejs" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Step 4: Restart Shell to Load PATH
      - name: Reload Environment Variables
        shell: powershell
        run: |
          $env:Path += ";C:\ProgramData\nvm;C:\Program Files\nodejs"

      # Step 5: Install and Use Node.js via NVM
      - name: Install and Use Node.js via NVM
        shell: cmd
        run: |
          nvm install ${{ inputs.node_version }}
          nvm use ${{ inputs.node_version }}
          node -v
          npm -v
