name: Setup Node on Windows with NVM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Step 1: Install NVM and Node.js in one step
      - name: Install NVM and Node.js in one step
        shell: cmd
        run: |
          echo Installing NVM via Chocolatey...
          choco install nvm -y
          
          call refreshenv
 
          echo Installing Node.js version: ${{ inputs.version }}
          nvm install ${{ inputs.version }}
          nvm use ${{ inputs.version }}
 
          echo Verifying installations...
          node -v
          nvm -v
