name: Setup Node with choco on Windows with NVM
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
jobs:
  run-nvm:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
 
      - name: Download NVM for Windows installer
        run: |
          Invoke-WebRequest  https://github.com/coreybutler/nvm-windows/releases/download/1.2.2/nvm-noinstall.zip -OutFile nvm-noinstall.zip
          Expand-Archive -Path "nvm-noinstall.zip" -DestinationPath "C:\nvm" -Force
          #Get-ChildItem -Path "C:\nvm" -Recurse
          #pwd
          #Get-ChildItem -Path "D:\a\NPM-Main\NPM-Main" -Recurse
          Copy-Item "D:\a\NPM-Main\NPM-Main\settings.txt" "C:\nvm\settings.txt" -Force
          #Get-content "C:\nvm\settings.txt"
          
      - name: Set Environment variables for NVM
        run: |
         echo "NVM_HOME=C:\nvm" >>$env:GITHUB_ENV
         echo "NVM_SYMLINK=C:\nvm\nodejs" >>$env:GITHUB_ENV
         
      #- name: List available Node versions
      # run: |
      #  C:\nvm\nvm.exe list available
      
      - name: Install The Multiple NVM Versions
        run: |
          C:\nvm\nvm.exe  install 18.20.4
          C:\nvm\nvm.exe  install 18.19.1
          C:\nvm\nvm.exe  install 18.20.1
          C:\nvm\nvm.exe  install 15.0.0
          C:\nvm\nvm.exe  install 15.2.0
          C:\nvm\nvm.exe  install 15.4.0

      - name: List of the Installed NVM Versions
        run: nvm list    

          





          
