name: Setup Node With version txt

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check and switch Node.js version using NVM
        run: |
          $input = "${{ inputs.version }}".TrimStart("v")
          Write-Host "input versions:" $input

          # Validate if input version is empty
          if ([string]::IsNullOrWhiteSpace($input)) {
            Write-Error "Error: Input version is empty. Please provide a valid Node.js version."
            exit 1
          }
          
          $versions = Get-Content "versions.txt" | ForEach-Object { $_.Trim().TrimStart("v") }

          # List all available versions
            Write-Host "Available versions:" $versions | ForEach-Object { Write-Host $_ }

          $match = if($input -like "*`**") {
            $prefix = $input.TrimEnd('*')
            $versions | Where-Object { $_ -like "$prefix*" }
          } else {
            $versions | Where-Object { $_ -eq $input }
          }

          if (-not $match) {
            Write-Error " No matching version found for input: $input"
            exit 1
          } 
          # Optional: pick the first matching version
          $selectedVersion = $match | Sort-Object -Descending | Select-Object -First 1
          Write-Host " Matched version: $selectedVersion"
          echo "version=$selectedVersion" >> $env:GITHUB_ENV
          
          # Use NVM to switch Node.js version
          Write-Host " Switching Node.js version using NVM..."
          nvm use $selectedVersion

          # Confirm version
          node -v

         
