name: Setup Node on Windows with NVM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install NVM via Chocolatey
        run: |
          echo Installing NVM via Chocolatey...
          choco install nvm -y

      - name: Set environment variables for NVM
        run: |
          echo Setting environment variables...
          setx NVM_HOME "C:\Program Files\nvm"
          setx NVM_SYMLINK "C:\Program Files\nodejs"
          set "PATH=C:\Program Files\nvm;C:\Program Files\nodejs;%PATH%"

      - name: Verify NVM Installation
        run: |
          echo PATH=%PATH%
          where nvm
          nvm -v

      - name: Install Node.js via NVM
        shell: cmd
        run: |
          echo Restarting shell session for PATH update...
          nvm install 18.18.0
          nvm use 18.18.0

      - name: Check installed Node.js version
        run: node -v
 
          
