name: Node Main-Workflow 
 
on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

  
jobs:
  call-reusable:
    #uses: ./.github/workflows/node-reusable-workflow.yml
    uses: ./.github/workflows/node-choco.yml
    with:
      version: '18.0.0'
