name: Setup Node on Windows
 
on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
 
jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Install NVM for Windows
        run: |
          Invoke-WebRequest -Uri https://github.com/coreybutler/nvm-windows/releases/download/1.1.12/nvm-setup.exe -OutFile nvm-setup.exe
          Start-Process -FilePath .\nvm-setup.exe -Wait
 
      - name: Add NVM path to environment
        shell: powershell
        run: |
          echo "C:\Program Files\nvm" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\nodejs" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
 
      - name: Install and use Node.js version
        run: |
          nvm install ${{ inputs.node_version }}
          nvm use ${{ inputs.node_version }}
          node -v
          npm -v
