name: NPM Main Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: NPM Install
        uses: ./.github/actions/npm-actions
        with:
          command: "publish"
          workingDir: "."
          verbose: true
          customCommand: ""
          customRegistry: "https://registry.npmjs.org/"
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
 
      - name: NPM Build
        uses: ./.github/actions/npm-actions
        with:
          command: "custom"
          workingDir: "."
          verbose: true
          customCommand: "run build"
          customRegistry: "https://registry.npmjs.org/"
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
