name: NPM Main Workflow

on: 
  push: 
    branches: 
      - main
  #workflow_dispatch: 

jobs: 
  call-reusable: 
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest] 
    uses: ./.github/workflows/npmtask-reusable.yml
    with: 
      runsOn: ${{ matrix.os }}
      command: "custom" 
      workingDir: "."
      verbose: true 
      customCommand: "run build:fonts" 
      customRegistry: "https://registry.npmjs.org/" 
     
