name: NPM Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  #checkout:
    #runs-on: windows-latest
    #steps:
      #- name: Checkout repository
        #uses: actions/checkout@v4

  call-reusable:
    #needs: checkout
    uses: ./.github/workflows/npmtask-reusable.yml
    with:
      runsOn: windows-latest
      command: "custom"
      workingDir: "./workflow/path"
      verbose: true
      customCommand: "run build:fonts"
      customRegistry: "https://registry.npmjs.org/"
