name: NPM Main Workflow

on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs: 
  call-reusable: 
    uses: ./.github/workflows/npmtask-reusable.yml
    with: 
      command: "install" 
      workingDir: "."
      verbose: false 
      customCommand: "run build:fonts" 
      customRegistry: "https://registry.npmjs.org/" 
     
