name: NPM
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/npmtask-reusable.yml
    secrets:  
      username: ${{ secrets.NEXUS_USERNAME }}  # Pass the secret username
      password: ${{ secrets.NEXUS_PASSWORD }}  # Pass the secret password
    with:
      runsOn: windows-latest
      command: "publish"
      workingDir: "."
      verbose: true
      customCommand: "run build:fonts"
      customRegistry: "https://registry.npmjs.org/"
