#################################################
# Workflow Name : Npm
# Description : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts."
# Version : v1
#################################################

name: Npm

on:
  workflow_call:
    inputs:
      runsOn:
        description: 'Specifies the runner to be used (e.g., windows-latest, ubuntu-latest)'
        required: true
        type: string
      command:
        description: 'Specifies the NPM command to be executed. Examples: "install" for installing dependencies'
        required: true
        type: string
      workingDir:
        description: 'Specifies the working directory where the NPM commands will be executed'
        required: true
        type: string
        default: "."
      verbose:
        description: 'Enables verbose output for NPM commands when set to true. Useful for debugging or detailed logging'
        required: false
        type: boolean
        default: false
      customCommand:
        description: 'Specifies a custom NPM command to be executed. This input is mandatory when the command input is set to "custom".'
        required: false
        type: string
      customRegistry:
        description: 'Specifies a custom NPM registry URL. If provided, this registry will be configured in the .npmrc file before executing commands'
        required: false
        type: string 

jobs:
  npm-task:
    runs-on: ${{ inputs.runsOn }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: NPM Task Header
        run: |
            # Task Header
            Write-Host "===================================================================================================="
            Write-Host "Task        : Npm"
            Write-Host "Description : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts."
            Write-Host "Version     : v1"
            Write-Host "===================================================================================================="
      
      - name: Install Dependencies
        run: npm install
        shell: pwsh

      - name: Validate Working Directory
        if: ${{ inputs.workingDir != '' }}
        shell: pwsh
        run: |
          if (-Not (Test-Path -Path "${{ inputs.workingDir }}")) {
            Write-Error "The specified working directory '${{ inputs.workingDir }}' does not exist."
            exit 1
          } else {
            Write-Host "Working directory '${{ inputs.workingDir }}' exists."
          }

      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        working-directory: ${{ inputs.workingDir }}
        shell: pwsh
        run: |
          try {
            Add-Content -Path .npmrc -Value "registry=${{ inputs.customRegistry }}"
            Write-Host "Custom registry configured: ${{ inputs.customRegistry }}"
          } catch {
            Write-Error "Failed to configure custom registry: $_"
            exit 1
          }

      - name: Run NPM or Custom Command
        working-directory: ${{ inputs.workingDir }}
        shell: pwsh
        run: |
          try {
            $allowedCommands = @("custom", "install", "ci")
            if (-not $allowedCommands.Contains("${{ inputs.command }}")) {
              Write-Error "Error: Invalid command '${{ inputs.command }}'. Allowed commands are: custom, install, ci."
              exit 1
            }
      
            if ("${{ inputs.command }}" -eq "custom") {
              if ([string]::IsNullOrEmpty("${{ inputs.customCommand }}")) {
                Write-Error "Error: customCommand input is required when command is 'custom'"
                exit 1
              } else {
                if ("${{ inputs.verbose }}" -eq "true") {
                  Write-Host "Running Custom Command: ${{ inputs.customCommand }} --verbose"
                  npm ${{ inputs.customCommand }} --verbose
                } else {
                  Write-Host "Running Custom Command: ${{ inputs.customCommand }}"
                  npm ${{ inputs.customCommand }}
                }
              }
            } else {
              if ("${{ inputs.verbose }}" -eq "true") {
                Write-Host "Running npm ${{ inputs.command }} --verbose"
                npm ${{ inputs.command }} --verbose
              } else {
                Write-Host "Running npm ${{ inputs.command }}"
                npm ${{ inputs.command }}
              }
            }
          } catch {
            Write-Error "An error occurred while executing the npm logic: $_"
            exit 1
          }
