name: Reusable NPM Workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      workingDir:
        required: true
        type: string
        default: "."
      verbose:
        required: false
        type: boolean
        default: false
      customCommand:
        required: false
        type: string
      customRegistry:
        required: false
        type: string 

jobs:
  npm-task:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: npm install
        shell: powershell

      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        working-directory: ${{ inputs.workingDir }}
        run: |
          $registry = '${{ inputs.customRegistry }}'
          "registry=$registry" | Out-File -FilePath .npmrc -Encoding utf8 -Append
        shell: powershell

      - name: Run NPM or Custom Command
        working-directory: ${{ inputs.workingDir }}
        shell: powershell
        run: |
          $cmd = '${{ inputs.command }}'
          $verbose = '${{ inputs.verbose }}'
          $custom = '${{ inputs.customCommand }}'
       
          if ($cmd -in @('install', 'publish', 'custom')) {
            if ($cmd -eq 'custom') {
              if ([string]::IsNullOrEmpty($custom)) {
                Write-Error "Error: customCommand input is required when command is 'custom'"
                exit 1
              } else {
                Write-Host "Running Custom Command: $custom"
                npm $custom
              }
            } elseif ($verbose -eq 'true') {
              Write-Host "Running npm $cmd --verbose"
              npm $cmd --verbose
            } else {
              Write-Host "Running npm $cmd"
              npm $cmd
            }
       
            Write-Host "Node.js Version:"
            node -v
          } else {
            Write-Error "Error: Unsupported command '$cmd'. Only 'install', 'publish', or 'custom' are allowed."
            exit 1
          }
        
