name: Reusable NPM Workflow

on:
  workflow_call:
    inputs:
      runsOn:
        description: 'Specifies the runner to be used (e.g., windows-latest, ubuntu-latest)'
        required: true
        type: string
      command:
        description: 'Specifies the NPM command to be executed. Examples: "install" for installing dependencies'
        required: true
        type: string
      workingDir:
        description: 'Specifies the working directory where the NPM commands will be executed'
        required: true
        type: string
        default: "."
      verbose:
        description: 'Enables verbose output for NPM commands when set to true. Useful for debugging or detailed logging'
        required: false
        type: boolean
        default: false
      customCommand:
        description: 'Specifies a custom NPM command to be executed. This input is mandatory when the command input is set to "custom".'
        required: false
        type: string
      customRegistry:
        description: 'Specifies a custom NPM registry URL. If provided, this registry will be configured in the .npmrc file before executing commands'
        required: false
        type: string 

jobs:
  npm-task:
    runs-on: ${{ inputs.runsOn }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: npm install
        shell: pwsh

      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        working-directory: ${{ inputs.workingDir }}
        run: |
          Add-Content -Path .npmrc -Value "registry=${{ inputs.customRegistry }}"
        shell: pwsh

      - name: Run NPM or Custom Command
        working-directory: ${{ inputs.workingDir }}
        shell: pwsh
        run: |
          if ("${{ inputs.command }}" -eq "custom") {
            if ([string]::IsNullOrEmpty("${{ inputs.customCommand }}")) { 
              Write-Error "Error: customCommand input is required when command is 'custom'"
              exit 1
            } else {
              if ("${{ inputs.verbose }}" -eq "true") {
                Write-Host "Running Custom Command: ${{ inputs.customCommand }} --verbose"
                npm ${{ inputs.customCommand }} --verbose
              } else {
                Write-Host "Running Custom Command: ${{ inputs.customCommand }}"
                npm ${{ inputs.customCommand }}
              }
            }
          } else {
            if ("${{ inputs.verbose }}" -eq "true") {
              Write-Host "Running npm ${{ inputs.command }} --verbose"
              npm ${{ inputs.command }} --verbose
            } else {
              Write-Host "Running npm ${{ inputs.command }}"
              npm ${{ inputs.command }}
            }
          }  
