name: Reusable NPM Workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      workingDir:
        required: true
        type: string
        default: "."
      verbose:
        required: false
        type: boolean
        default: false
      customCommand:
        required: false
        type: string
      customRegistry:
        required: false
        type: string 

jobs:
  npm-task:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: npm install
        shell: cmd

      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        working-directory: ${{ inputs.workingDir }}
        run: |
          echo registry=${{ inputs.customRegistry }} >> .npmrc
        shell: cmd

      - name: Run NPM or Custom Command
        working-directory: ${{ inputs.workingDir }}
        run: |
          echo Node.js Version After  : && node -v 
          if "${{ inputs.command }}"=="custom" (
            if "${{ inputs.customCommand }}"=="" (
              echo Error: customCommand input is required when command is "custom"
              exit 1
            ) else (
              echo Running Custom Command: ${{ inputs.customCommand }}
              npm ${{ inputs.customCommand }}
            )
          ) else if "${{ inputs.verbose }}"=="true" (
            echo Running npm ${{ inputs.command }} --verbose
            npm ${{ inputs.command }} --verbose
          ) else (
            echo Running npm ${{ inputs.command }}
            npm ${{ inputs.command }}
          )
          echo Node.js Version : && node -v
        shell: cmd

