name: Reusable NPM Workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      workingDir:
        required: false
        type: string
        default: '.'
      verbose:
        required: false
        type: boolean
        default: false
      customCommand:
        required: false
        type: string
      customRegistry:
        required: false
        type: string

jobs:
  npm-task:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        run: |
          echo registry=${{ inputs.customRegistry }} >> .npmrc

      - name: Run NPM Command
        shell: cmd
        working-directory: ${{ inputs.workingDir }}
        run: |
          if "%{{ inputs.verbose }}"=="true" (
            npm ${{ inputs.command }} --verbose
          ) else (
            npm ${{ inputs.command }}
          )

      - name: Run Custom Command
        if: ${{ inputs.customCommand != '' }}
        shell: cmd
        working-directory: ${{ inputs.workingDir }}
        run: |
          ${{ inputs.customCommand }}
