name: Reusable NPM Workflow

on:
  workflow_call:
    inputs:
      command:
        description: 'Specifies the NPM command to be executed. Examples: "install" for installing dependencies'
        required: true
        type: string
      workingDir:
        description: 'Specifies the working directory where the NPM commands will be executed'
        required: true
        type: string
        default: "."
      verbose:
        description: 'Enables verbose output for NPM commands when set to true. Useful for debugging or detailed logging'
        required: false
        type: boolean
        default: false
      customCommand:
        description: 'Specifies a custom NPM command to be executed. This input is mandatory when the command input is set to "custom".'
        required: false
        type: string
      customRegistry:
        description: 'Specifies a custom NPM registry URL. If provided, this registry will be configured in the .npmrc file before executing commands'
        required: false
        type: string 

jobs:
  npm-task:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: npm install
        shell: cmd

      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        working-directory: ${{ inputs.workingDir }}
        run: |
          echo registry=${{ inputs.customRegistry }} >> .npmrc
        shell: cmd

      - name: Run NPM or Custom Command
        working-directory: ${{ inputs.workingDir }}
        shell: cmd
        run: |
          if "${{ inputs.command }}"=="custom" (
            if "${{ inputs.customCommand }}"=="" (
              echo Error: customCommand input is required when command is "custom"
              exit 1
            ) else (
              if "${{ inputs.verbose }}"=="true" (
                echo Running Custom Command: ${{ inputs.customCommand }} --verbose
                npm ${{ inputs.customCommand }} --verbose
              ) else (
                echo Running Custom Command: ${{ inputs.customCommand }}
                npm ${{ inputs.customCommand }}
              )
            )
          ) else (
            if "${{ inputs.verbose }}"=="true" (
              echo Running npm ${{ inputs.command }} --verbose
              npm ${{ inputs.command }} --verbose
            ) else (
              echo Running npm ${{ inputs.command }}
              npm ${{ inputs.command }}
            )
          )
          echo Node.js Version After : && node -v
