name: Reusable NPM Workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      workingDir:
        required: true
        type: string
      verbose:
        required: false
        type: boolean
        default: false
      customCommand:
        required: false
        type: string
      customRegistry:
        required: false
        type: string

jobs:
  npm-task:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Working Directory Contains package.json
        run: |
          if not exist "%{{ inputs.workingDir }}\package.json" (
            echo Error: package.json not found in the specified working directory: %{{ inputs.workingDir }} && exit /b 1
          )
        shell: cmd

      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        working-directory: ${{ inputs.workingDir }}
        run: |
          echo registry=${{ inputs.customRegistry }} >> .npmrc
        shell: cmd

      - name: Run NPM Command
        working-directory: ${{ inputs.workingDir }}
        run: |
          if "%{{ inputs.verbose }}"=="true" (
            npm ${{ inputs.command }} --verbose
          ) else (
            npm ${{ inputs.command }}
          )
        shell: cmd

      - name: Run Custom Command
        if: ${{ inputs.customCommand != '' }}
        working-directory: ${{ inputs.workingDir }}
        run: |
          %{{ inputs.customCommand }}
        shell: cmd
