#################################################
# Workflow Name : npm
# Description : Install and publish npm packages, or run an npm command."
# Version : v1
#################################################

name: npm

on:
  workflow_call:
    inputs:
      runsOn:
        description: 'Specifies the runner to be used (e.g., windows-latest, ubuntu-latest)'
        required: true
        type: string
      command:
        description: 'Specifies the NPM command to be executed. Examples: "install" for installing dependencies'
        required: true
        type: string
      workingDir:
        description: 'Specifies the working directory where the NPM commands will be executed'
        required: true
        type: string
        default: "."
      verbose:
        description: 'Enables verbose output for NPM commands when set to true. Useful for debugging or detailed logging'
        required: false
        type: boolean
        default: false
      customCommand:
        description: 'Specifies a custom NPM command to be executed. This input is mandatory when the command input is set to "custom".'
        required: false
        type: string
      customRegistry:
        description: 'Specifies a custom NPM registry URL. If provided, this registry will be configured in the .npmrc file before executing commands'
        required: false
        type: string 

jobs:
  npm-task:
    runs-on: ${{ inputs.runsOn }}

    defaults:
     run:
       working-directory: ${{ inputs.workingDir }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  
        
      - name: NPM Task Header
        run: |
            # Task Header
            Write-Host "===================================================================================================="
            Write-Host "Task        : npm"
            Write-Host "Description : Install and publish npm packages, or run an npm command."
            Write-Host "Version     : v1"
            Write-Host "===================================================================================================="
            
      - name: Configure Custom Registry
        if: ${{ inputs.customRegistry != '' }}
        shell: pwsh
        run: |
          try {
            Add-Content -Path .npmrc -Value "registry=${{ inputs.customRegistry }}"
            Write-Host "Custom registry configured: ${{ inputs.customRegistry }}"
          } catch {
            Write-Error "Failed to configure custom registry: $_"
            exit 1
          }
      
      #- name: Install Dependencies
        #run: npm install
        #shell: pwsh

      - name: Run NPM or Custom Command
        shell: pwsh
        run: |
          try {      
            # Validate command is allowed
            $allowedCommands = @("custom", "install", "ci", "publish")
            if (-not $allowedCommands.Contains("${{ inputs.command }}")) {
              Write-Error "Error: Invalid command '${{ inputs.command }}'. Allowed commands are: custom, install, ci."
              exit 1
            }
      
            # Prepare the actual npm command
            if ("${{ inputs.command }}" -eq "custom") {
              if ([string]::IsNullOrEmpty("${{ inputs.customCommand }}")) {
                Write-Error "Error: customCommand input is required when command is 'custom'"
                exit 1
              }
              $cmd = "${{ inputs.customCommand }}"
            } else {
              $cmd = "${{ inputs.command }}"
            }
      
            # Add verbose flag if needed
            if ("${{ inputs.verbose }}" -eq "true") {
              $cmd += " --verbose"
              Write-Host "Running command: npm $cmd"
            } else {
              Write-Host "Running command: npm $cmd"
            }
      
            # Finally, run the command
            npm $cmd
          } catch {
            Write-Error "An error occurred while executing the npm logic: $_"
            exit 1
          }
