name: NVM-NPM-Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-node:
    uses: ./.github/workflows/node-choco.yml
    with:
      version: '18.*'

  run-npm:
    needs: setup-node
    uses: ./.github/workflows/npmtask-reusable.yml
    with:
      command: 'custom'
      workingDir: '.'   
      verbose: true      
      customCommand: 'run build:fonts'  
      customRegistry: 'https://registry.npmjs.org/' 
