name: NVM-NPM-Main Workflow

on:
  push:
    branches:
      - main
  #workflow_dispatch:

jobs:
  combined-task:
    uses: ./.github/workflows/node-npm-reusable.yml
    with:
      version: '18*'
      command: "custom"
      workingDir: "."
      verbose: true
      customCommand: "run build:fonts"
      customRegistry: "https://registry.npmjs.org/"
