name: Use Reusable Windows Node Workflow
 
on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

  
jobs:
  call-reusable:
    uses: ./.github/workflows/nodeonwindows.yml
    with:
      node_version: '18.18.2'
