name: Manual NVM Run on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-nvm:
    runs-on: windows-latest

    steps:
      - name: Download NVM for Windows installer
        shell: powershell
        run: |
          Invoke-WebRequest https://github.com/coreybutler/nvm-windows/releases/latest/download/nvm-setup.exe -OutFile nvm-setup.exe

      - name: Install NVM
        shell: powershell
        run: |
          Start-Process -FilePath .\nvm-setup.exe -ArgumentList '/SILENT' -Wait

      - name: Add NVM and Node to PATH
        shell: powershell
        run: |
          $env:Path += ";C:\Program Files\nvm;C:\Program Files\nodejs"
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Machine)

      - name: List available Node versions
        shell: cmd
        run: |
          nvm list available

      - name: Install and use Node 18.18.2
        shell: cmd
        run: |
          nvm install 18.18.2
          nvm use 18.18.2
          node -v
