 name: Manual NVM Run on Windows
 
on:
  workflow_dispatch:
 
jobs:
  run-nvm:
    runs-on: windows-latest
 
    steps:
      - name: Download NVM for Windows installer
        run: |
          Invoke-WebRequest https://github.com/coreybutler/nvm-windows/releases/latest/download/nvm-setup.exe -OutFile nvm-setup.exe
 
      - name: Install NVM
        run: |
          Start-Process .\nvm-setup.exe -Wait
 
      - name: Add NVM and Node to PATH
        shell: powershell
        run: |
          $env:Path += ";C:\Program Files\nvm;C:\Program Files\nodejs"
          [System.Environment]::SetEnvironmentVariable("Path", $env:Path, [System.EnvironmentVariableTarget]::Process)
 
      - name: List available Node versions
        run: |
          nvm list available
 
      - name: Install and use Node 18.18.2
        run: |
          nvm install 18.18.2
          nvm use 18.18.2
          node -v
 
