name: Portal-AI-Pipelines
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  UMB_UCD_Name: "YourValueHere."

jobs:
  Portal-AI-Pipelines:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure NPM Registry
        shell: pwsh
        run: |
          
          npm config set registry="http://10.0.0.5:8081/repository/npm-group/"
          npm config set //10.0.0.5:8081/repository/npm-group/:username=${{ secrets.NEXUS_USERNAME }}
          npm config set //10.0.0.5:8081/repository/npm-group/:password=${{ secrets.NEXUS_PASSWORD }}
 
      - name: NPM Install
        uses: ./.github/actions/npm-actions
        with:
          command: "custom"
          workingDir: "."
          verbose: true
          customCommand: "install --no-save"
          customRegistry: "http://10.0.0.5:8081/repository/npm-group/"
          #nexus_username: ${{ secrets.NEXUS_USERNAME }}
          #nexus_password: ${{ secrets.NEXUS_PASSWORD }}
