name: Portal-AI-Pipelines
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  UMB_UCD_Name: "YourValueHere."

jobs:
  Portal-AI-Pipelines:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: config .npmrc
        shell: pwsh
        run: |
            $npmrc_file_path="C:\Users\azureuser\.npmrc"
            if (Test-Path $npmrc_file_path) {
              Remove-Item $npmrc_file_path -Force
              Write-Host "user level .npmrc file removed"
            }
            else {
            Write-Host "$npmrc_file_path does not exist"
            }   

      - name: Configure NPM Registry
        shell: pwsh
        run: |
          $authString = "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}"
          $authBase64 = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($authString))
          $npmrcPath = "${{ github.workspace }}\.npmrc"

          npm config set registry "http://10.0.0.5:8081/repository/npm-group/" --userconfig $npmrcPath
          npm config set //10.0.0.5:8081/repository/npm-group/:_auth $authBase64 --userconfig $npmrcPath
          

      - name: Verify .npmrc Path
        shell: pwsh
        run: |
          $npmrcPath = "${{ github.workspace }}\.npmrc"
          Get-Content $npmrcPath    
 
      - name: NPM Install
        uses: ./.github/actions/npm-actions
        with:
          command: "custom"
          workingDir: "."
          verbose: true
          customCommand: "install --no-save"
          customRegistry: "http://10.0.0.5:8081/repository/npm-group/"
          #nexus_username: ${{ secrets.NEXUS_USERNAME }}
          #nexus_password: ${{ secrets.NEXUS_PASSWORD }}
