name: Portal-AI-Pipelines
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  UMB_UCD_Name: "YourValueHere"

jobs:
  Portal-AI-Pipelines:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: NPM Install
        uses: ./.github/actions/npm-actions
        with:
          command: "custom"
          workingDir: "."
          verbose: true
          customCommand: "install --no-save"
          customRegistry: "http://10.0.0.5:8081/repository/npm/"
          nexus_username: ${{ secrets.NEXUS_USERNAME }}
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}  
 
      - name: NPM Build
        uses: ./.github/actions/npm-actions
        with:
          command: "custom"
          workingDir: "."
          verbose: true
          customCommand: "run build"
          customRegistry: "http://10.0.0.5:8081/repository/npm/" 
          
      - name: Copy Generated Files to 
        uses: Prakasha3007/Copy-Files/.github/actions/copyfile-actions@main
        with:
          SourceFolder: sourcefolder
          contents: '**'
          TargetFolder: targetFolder
          CleanTargetFolder: true
          overwrite: false
          FlattenFolders: false
          preserveTimestamp: false
          retryCount: '3'
          delayBetweenRetries: '5000'
          ignoreMakeDirErrors: false 

      - name: Copy Public Files to 
        uses: Prakasha3007/Copy-Files/.github/actions/copyfile-actions@main
        with:
          SourceFolder: sourcefolder
          contents: '*.txt'
          TargetFolder: targetFolder
          CleanTargetFolder: true
          overwrite: false
          FlattenFolders: false
          preserveTimestamp: false
          retryCount: '3'
          delayBetweenRetries: '5000'
          ignoreMakeDirErrors: false  

      - name: PowerShell Script
        uses: Prakasha3007/PowerShell/.github/actions/pshell-actions@main
        with:
          targetType: filePath
          filePath: 'scripts/sample-script.ps1'
          arguments: 'arg1 arg2'
          script: hostname
          workingFolder: '.'
          errorPreference: Stop
          ignoreLASTEXITCODE: false
